/* test data */
insert into api.tags (name, adult) values ('Sci-Fi', false), ('Test', false);

insert into api.tags (name)
values
    ('Abduction'),
    ('Abuse'),
    ('Action/Adventure'),
    ('Age Difference'),
    ('Alcohol'),
    ('Alpha/Beta/Omega Dynamics'),
    ('Ambiguity'),
    ('Angst'),
    ('Anxiety'),
    ('Art'),
    ('Asphyxiation'),
    ('Awkwardness'),
    ('Badass'),
    ('Bathing/Washing'),
    ('BDSM'),
    ('Beds'),
    ('Birthday'),
    ('Biting'),
    ('Blood'),
    ('Bodily Fluids'),
    ('Bonding'),
    ('Bottoming'),
    ('Break Up'),
    ('Children'),
    ('Clothing'),
    ('Coercion'),
    ('Comfort'),
    ('Confessions'),
    ('Consent'),
    ('Crack'),
    ('Crimes & Criminals'),
    ('Crushes'),
    ('Crying'),
    ('Cuddling & Snuggling'),
    ('Dancing & Singing'),
    ('Dark'),
    ('Dating'),
    ('Death'),
    ('Disability'),
    ('Domestic'),
    ('Drama'),
    ('Dreams and Nightmares'),
    ('Drugs'),
    ('Education'),
    ('Enemies'),
    ('Everyone Is Alive'),
    ('Falling In Love'),
    ('Family'),
    ('Feelings'),
    ('Feels'),
    ('Female Relationships'),
    ('Fights'),
    ('Firsts'),
    ('Flashbacks'),
    ('Flirting'),
    ('Fluff'),
    ('Food'),
    ('Friendship'),
    ('Getting Together'),
    ('Gore'),
    ('Guilt'),
    ('Hair'),
    ('Happy'),
    ('Harm to Children'),
    ('Hatred'),
    ('Heroes & Heroines'),
    ('Higher Education'),
    ('Historical'),
    ('Holidays'),
    ('Homophobia'),
    ('Horror'),
    ('Hugs'),
    ('Human'),
    ('Humiliation'),
    ('Humor'),
    ('Hurt'),
    ('Hurt/Comfort'),
    ('Illnesses'),
    ('Implied/Referenced Character Death'),
    ('Incest'),
    ('Infidelity'),
    ('Injury'),
    ('Intoxication'),
    ('Introspection'),
    ('Issues'),
    ('Jealousy'),
    ('Kinks'),
    ('Kissing'),
    ('Language'),
    ('LGBTQ Themes'),
    ('Light-Hearted'),
    ('Loss'),
    ('Love'),
    ('Making Out'),
    ('Manipulation'),
    ('Marriage'),
    ('Medical'),
    ('Memory Related'),
    ('Mental Health Issues'),
    ('Misunderstandings'),
    ('Modern Era'),
    ('Music'),
    ('Mystery'),
    ('Mythical Beings & Creatures'),
    ('Pain'),
    ('Panic'),
    ('Pining'),
    ('Poetry'),
    ('Polyamory'),
    ('Pregnancy'),
    ('Protectiveness'),
    ('Religion'),
    ('Restaurants'),
    ('Romance'),
    ('Royalty'),
    ('Sad'),
    ('Science Fiction & Fantasy'),
    ('Self-Esteem'),
    ('Self-Harm'),
    ('Sexual Content'),
    ('Shapeshifting'),
    ('Sharing'),
    ('Slash'),
    ('Slice of Life'),
    ('Slow Build'),
    ('Soulmates'),
    ('Sports'),
    ('Substance Abuse'),
    ('Suicide'),
    ('Supernatural Elements'),
    ('Teasing'),
    ('Teenagers'),
    ('Tension'),
    ('Threesome'),
    ('Time Travel'),
    ('Topping'),
    ('Torture'),
    ('Trauma'),
    ('Unrequited'),
    ('Violence'),
    ('Voyeurism'),
    ('War'),
    ('Weather')
;

insert into api.books (title, author, isbn, cover, description)
values
    ('The Martian', 'Andy Weir', '9780593357132', 'http://books.google.com/books/content?id=OPAgEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', '#1 NEW YORK TIMES BESTSELLER • “Brilliant . . . a celebration of human ingenuity [and] the purest example of real-science sci-fi for many years . . . utterly compelling.”—The Wall Street Journal The inspiration for the major motion picture Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he’s sure he’ll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive—and even if he could get word out, his supplies would be gone long before a rescue could arrive. Chances are, though, he won’t have time to starve to death. The damaged machinery, unforgiving environment, or plain-old “human error” are much more likely to kill him first. But Mark isn’t ready to give up yet. Drawing on his ingenuity, his engineering skills—and a relentless, dogged refusal to quit—he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him? NAMED ONE OF PASTE’S BEST NOVELS OF THE DECADE “A hugely entertaining novel [that] reads like a rocket ship afire . . . Weir has fashioned in Mark Watney one of the most appealing, funny, and resourceful characters in recent fiction.”—Chicago Tribune “As gripping as they come . . . You’ll be rooting for Watney the whole way, groaning at every setback and laughing at his pitchblack humor. Utterly nail-biting and memorable.”—Financial Times'),
    ('The Lightning Thief', 'Rick Riordan', '9781423140344', 'https://books.google.com/books/content?id=MpC3_SuCss4C&printsec=frontcover&img=0&zoom=1&edge=curl&source=gbs_api', 'Percy Jackson is about to be kicked out of boarding school...again. And that''s the least of his troubles. Lately, mythological monsters and the gods of Mount Olympus seem to be walking straight out of the pages of Percy''s Greek mythology textbook and into his life. Book #1 in the NYT best-selling series, with cover art from the feature film, The Lightning Thief.'),
    ('The Dragonet Prophecy', 'Tui T. Sutherland', '9781338883190', 'http://books.google.com/books/content?id=ezIuzwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Discover where it all began! The #1 New York Times and USA Today bestselling series takes flight in this epic adventure of five dragons destined and determined to save their world. Clay has lived his whole life under the mountain. The MudWing dragonet knows that war is raging between the dragon tribes in the world outside -- a war that he and four other dragonets are destined to end, according to the mysterious Prophecy they''ve been taught. The five chosen dragonets were stolen from their homes while they were still in their eggs and hidden away ever since -- all to fulfill the Prophecy. But not every dragonet wants a destiny. And when danger threatens one of their own, Clay and his friends must choose freedom over fate . . . leave the mountain . . . and set the dragon world on a course that no one could have predicted.')
;

insert into api.tagmap (book_id, tag_id) values (1, 5), (1, 10), (1, 15), (1, 20), (2, 1), (2, 2), (2, 5), (2, 10), (3, 2), (3, 1), (3, 7), (3, 8);