/* test data */
insert into api.tags (name, adult) values ('Sci-Fi', false), ('Test', false);

insert into api.tags (name)
values
    ('Abduction'),
    ('Abuse'),
    ('Action/Adventure'),
    ('Age Difference'),
    ('Alcohol'),
    ('Alpha/Beta/Omega Dynamics'),
    ('Ambiguity'),
    ('Angst'),
    ('Anxiety'),
    ('Art'),
    ('Asphyxiation'),
    ('Awkwardness'),
    ('Badass'),
    ('Bathing/Washing'),
    ('BDSM'),
    ('Beds'),
    ('Birthday'),
    ('Biting'),
    ('Blood'),
    ('Bodily Fluids'),
    ('Bonding'),
    ('Bottoming'),
    ('Break Up'),
    ('Children'),
    ('Clothing'),
    ('Coercion'),
    ('Comfort'),
    ('Confessions'),
    ('Consent'),
    ('Crack'),
    ('Crimes & Criminals'),
    ('Crushes'),
    ('Crying'),
    ('Cuddling & Snuggling'),
    ('Dancing & Singing'),
    ('Dark'),
    ('Dating'),
    ('Death'),
    ('Disability'),
    ('Domestic'),
    ('Drama'),
    ('Dreams and Nightmares'),
    ('Drugs'),
    ('Education'),
    ('Enemies'),
    ('Everyone Is Alive'),
    ('Falling In Love'),
    ('Family'),
    ('Feelings'),
    ('Feels'),
    ('Female Relationships'),
    ('Fights'),
    ('Firsts'),
    ('Flashbacks'),
    ('Flirting'),
    ('Fluff'),
    ('Food'),
    ('Friendship'),
    ('Getting Together'),
    ('Gore'),
    ('Guilt'),
    ('Hair'),
    ('Happy'),
    ('Harm to Children'),
    ('Hatred'),
    ('Heroes & Heroines'),
    ('Higher Education'),
    ('Historical'),
    ('Holidays'),
    ('Homophobia'),
    ('Horror'),
    ('Hugs'),
    ('Human'),
    ('Humiliation'),
    ('Humor'),
    ('Hurt'),
    ('Hurt/Comfort'),
    ('Illnesses'),
    ('Implied/Referenced Character Death'),
    ('Incest'),
    ('Infidelity'),
    ('Injury'),
    ('Intoxication'),
    ('Introspection'),
    ('Issues'),
    ('Jealousy'),
    ('Kinks'),
    ('Kissing'),
    ('Language'),
    ('LGBTQ Themes'),
    ('Light-Hearted'),
    ('Loss'),
    ('Love'),
    ('Making Out'),
    ('Manipulation'),
    ('Marriage'),
    ('Medical'),
    ('Memory Related'),
    ('Mental Health Issues'),
    ('Misunderstandings'),
    ('Modern Era'),
    ('Music'),
    ('Mystery'),
    ('Mythical Beings & Creatures'),
    ('Pain'),
    ('Panic'),
    ('Pining'),
    ('Poetry'),
    ('Polyamory'),
    ('Pregnancy'),
    ('Protectiveness'),
    ('Religion'),
    ('Restaurants'),
    ('Romance'),
    ('Royalty'),
    ('Sad'),
    ('Science Fiction & Fantasy'),
    ('Self-Esteem'),
    ('Self-Harm'),
    ('Sexual Content'),
    ('Shapeshifting'),
    ('Sharing'),
    ('Slash'),
    ('Slice of Life'),
    ('Slow Build'),
    ('Soulmates'),
    ('Sports'),
    ('Substance Abuse'),
    ('Suicide'),
    ('Supernatural Elements'),
    ('Teasing'),
    ('Teenagers'),
    ('Tension'),
    ('Threesome'),
    ('Time Travel'),
    ('Topping'),
    ('Torture'),
    ('Trauma'),
    ('Unrequited'),
    ('Violence'),
    ('Voyeurism'),
    ('War'),
    ('Weather')
;